[package]
version = "0.1.0"
edition = "2024"
name = "persistence"
authors.workspace = true
rust-version.workspace = true

[dependencies]
models.workspace = true

diesel.workspace = true
deadpool-diesel.workspace = true
diesel_migrations.workspace = true

chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
